spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/micro_arch_db?authSource=admin
server:
  port: 8082
  servlet:
    context-path: "/api/order"