spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/micro_arch_db?authSource=admin
server:
  port: 8081
  servlet:
    context-path: "/api/product"